Traceback (most recent call last):
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\chjch\AppData\Local\ESRI\conda\envs\arcpro-py3-clone\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
query_numeric = """"POP2010" > 10000"""
zip_output = "zipbnd_q1"
arcpy.Select_analysis(zip_fc, zip_output, query_numeric)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mExecuteError[0m                              Traceback (most recent call last)
[1;32m<ipython-input-13-a87d43a5811f>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mquery_numeric[0m [1;33m=[0m [1;34m""""POP2010" > 10000"""[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mzip_output[0m [1;33m=[0m [1;34m"zipbnd_q1"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0marcpy[0m[1;33m.[0m[0mSelect_analysis[0m[1;33m([0m[0mzip_fc[0m[1;33m,[0m [0mzip_output[0m[1;33m,[0m [0mquery_numeric[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mC:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py[0m in [0;36mSelect[1;34m(in_features, out_feature_class, where_clause)[0m
[0;32m    136[0m         [1;32mreturn[0m [0mretval[0m[1;33m[0m[1;33m[0m[0m
[0;32m    137[0m     [1;32mexcept[0m [0mException[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 138[1;33m         [1;32mraise[0m [0me[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    139[0m [1;33m[0m[0m
[0;32m    140[0m [1;33m@[0m[0mgptooldoc[0m[1;33m([0m[1;34m'Split_analysis'[0m[1;33m,[0m [1;32mNone[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py[0m in [0;36mSelect[1;34m(in_features, out_feature_class, where_clause)[0m
[0;32m    133[0m     [1;32mfrom[0m [0marcpy[0m[1;33m.[0m[0marcobjects[0m[1;33m.[0m[0marcobjectconversion[0m [1;32mimport[0m [0mconvertArcObjectToPythonObject[0m[1;33m[0m[1;33m[0m[0m
[0;32m    134[0m     [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 135[1;33m         [0mretval[0m [1;33m=[0m [0mconvertArcObjectToPythonObject[0m[1;33m([0m[0mgp[0m[1;33m.[0m[0mSelect_analysis[0m[1;33m([0m[1;33m*[0m[0mgp_fixargs[0m[1;33m([0m[1;33m([0m[0min_features[0m[1;33m,[0m [0mout_feature_class[0m[1;33m,[0m [0mwhere_clause[0m[1;33m)[0m[1;33m,[0m [1;32mTrue[0m[1;33m)[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    136[0m         [1;32mreturn[0m [0mretval[0m[1;33m[0m[1;33m[0m[0m
[0;32m    137[0m     [1;32mexcept[0m [0mException[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py[0m in [0;36m<lambda>[1;34m(*args)[0m
[0;32m    510[0m         [0mval[0m [1;33m=[0m [0mgetattr[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_gp[0m[1;33m,[0m [0mattr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    511[0m         [1;32mif[0m [0mcallable[0m[1;33m([0m[0mval[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 512[1;33m             [1;32mreturn[0m [1;32mlambda[0m [1;33m*[0m[0margs[0m[1;33m:[0m [0mval[0m[1;33m([0m[1;33m*[0m[0mgp_fixargs[0m[1;33m([0m[0margs[0m[1;33m,[0m [1;32mTrue[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    513[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    514[0m             [1;32mreturn[0m [0mconvertArcObjectToPythonObject[0m[1;33m([0m[0mval[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mExecuteError[0m: Failed to execute. Parameters are not valid.
ERROR 000732: Input Features: Dataset zip_boundaries does not exist or is not supported
Failed to execute (Select).

ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Features: Dataset zip_boundaries does not exist or is not supported
Failed to execute (Select).


